/**
 * Advanced Example API
 * A comprehensive API spec demonstrating all OpenRPC features
 * Version: 2.0.0
 *
 * Auto-generated by py-openrpc-generator
 */

// ============================================================================
// Type Definitions
// ============================================================================

export interface User_getByIdParams {
  userId: string;
}

export interface User {
  id: string;
  name: string;
  email: string;
  age?: number;
  status: "active" | "inactive" | "suspended";
  createdAt: string;
}

export interface User_createParams {
  name: string;
  email: string;
  age?: number;
}

export interface User_updateParams {
  userId: string;
  data: {
  name?: string;
  email?: string;
};
}

export interface Notifications_subscribeParams {
  channel: "users" | "orders" | "system";
}

export interface Search_queryParams {
  query: string;
  filters?: {
  entityType?: "user" | "order" | "product";
  dateFrom?: string;
  dateTo?: string;
};
}

export interface Search_queryResult {
  items: {
  id: string;
  type: string;
  title: string;
  score: number;
}[];
  total: number;
}

// ============================================================================
// JSON-RPC Infrastructure
// ============================================================================

interface JsonRpcRequest {
  jsonrpc: "2.0";
  method: string;
  params?: any;
  id: number | string;
}

interface JsonRpcResponse<T = any> {
  jsonrpc: "2.0";
  result?: T;
  error?: {
    code: number;
    message: string;
    data?: any;
  };
  id: number | string;
}

// ============================================================================
// Error Classes
// ============================================================================

/**
 * Base class for JSON-RPC errors
 */
export class JsonRpcError extends Error {
  constructor(
    public code: number,
    message: string,
    public data?: any
  ) {
    super(`JSON-RPC Error ${code}: ${message}`);
    this.name = "JsonRpcError";
  }
}

/**
 * Application-specific error classes
 */
/**
 * Error 1001: User not found
 */
export class UserNotFoundError extends JsonRpcError {
  constructor(data?: any) {
    super(1001, "User not found", data);
    this.name = "UserNotFoundError";
  }
}

/**
 * Error 1004: Invalid user ID format
 */
export class InvalidUserIdFormatError extends JsonRpcError {
  constructor(data?: any) {
    super(1004, "Invalid user ID format", data);
    this.name = "InvalidUserIdFormatError";
  }
}

/**
 * Error 1002: Email already exists
 */
export class EmailAlreadyExistsError extends JsonRpcError {
  constructor(data?: any) {
    super(1002, "Email already exists", data);
    this.name = "EmailAlreadyExistsError";
  }
}

/**
 * Error 1003: Invalid email format
 */
export class InvalidEmailFormatError extends JsonRpcError {
  constructor(data?: any) {
    super(1003, "Invalid email format", data);
    this.name = "InvalidEmailFormatError";
  }
}


/**
 * Parse JSON-RPC error and throw appropriate error class
 */
function createJsonRpcError(code: number, message: string, data?: any): JsonRpcError {
  switch (code) {
    case 1001:
      return new UserNotFoundError(data);
    case 1004:
      return new InvalidUserIdFormatError(data);
    case 1002:
      return new EmailAlreadyExistsError(data);
    case 1003:
      return new InvalidEmailFormatError(data);
    default:
      return new JsonRpcError(code, message, data);
  }
}

// ============================================================================
// AdvancedAPIClient
// ============================================================================

export class AdvancedAPIClient {
  private url: string;
  private requestId: number = 0;

  constructor(url?: string) {
    this.url = url || "https://api.example.com/api/v2";
  }

  private async request<T = any>(method: string, params?: any): Promise<T> {
    const id = ++this.requestId;
    const body: JsonRpcRequest = {
      jsonrpc: "2.0",
      method,
      params,
      id,
    };

    const response = await fetch(this.url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(body),
    });

    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }

    const data: JsonRpcResponse<T> = await response.json();

    if (data.error) {
      throw createJsonRpcError(data.error.code, data.error.message, data.error.data);
    }

    return data.result as T;
  }

  private notify(method: string, params?: any): void {
    const body: JsonRpcRequest = {
      jsonrpc: "2.0",
      method,
      params,
      id: 0, // Notification uses id 0 or can be omitted
    };

    // Fire and forget - no need to wait for response
    fetch(this.url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(body),
    }).catch(() => {
      // Silently ignore errors for notifications
    });
  }

  // ==========================================================================
  // API Methods (organized by tags)
  // ==========================================================================

  // --------------------------------------------------------------------------
  // Users
  // --------------------------------------------------------------------------

  /**
   * Get user by ID
   *
   * Retrieves a user object by their unique identifier
   * @param params - Method parameters   *   - userId: The unique identifier of the user   * @returns The user object
   * @throws { 1001, 1004 }
   */
async user_getById(params: User_getByIdParams): Promise<User> {
return this.request<User>("user.getById", params);  }

  /**
   * Create a new user
   *
   * Creates a new user with the provided information
   * @param params - Method parameters   *   - name: User's full name   *   - email: User's email address   *   - age (optional): User's age   * @returns The created user object
   * @throws { 1002, 1003 }
   */
async user_create(params: User_createParams): Promise<User> {
return this.request<User>("user.create", params);  }

  /**
   * Update user (DEPRECATED)
   *
   * Updates an existing user. Use user.patch instead.
   * @deprecated This method is deprecated
   * @param params - Method parameters   *   - userId: The unique identifier of the user   *   - data: User data to update   */
/** @deprecated */
async user_update(params: User_updateParams): Promise<User> {
return this.request<User>("user.update", params);  }

  // --------------------------------------------------------------------------
  // Math
  // --------------------------------------------------------------------------

  /**
   * Add two numbers
   *
   * Returns the sum of two numbers using positional parameters
   * @param params - Method parameters (positional)   *   - a: First number   *   - b: Second number   * @returns The sum of a and b
   */
async math_add(params: [number, number]): Promise<number> {
return this.request<number>("math.add", params);  }

  // --------------------------------------------------------------------------
  // Notifications
  // --------------------------------------------------------------------------

  /**
   * Subscribe to notifications
   *
   * Subscribe to real-time notifications (notification method, no response expected)
   * @param params - Method parameters   *   - channel: Notification channel   */
async notifications_subscribe(params: Notifications_subscribeParams): Promise<void> {
this.notify("notifications.subscribe", params);  }

  // --------------------------------------------------------------------------
  // Search
  // --------------------------------------------------------------------------

  /**
   * Search across entities
   *
   * Performs a full-text search across multiple entity types
   * @param params - Method parameters   *   - query: Search query string   *   - filters (optional): Search filters   * @returns Search results
   */
async search_query(params: Search_queryParams): Promise<Search_queryResult> {
return this.request<Search_queryResult>("search.query", params);  }
}