// Example API
// A sample API for testing the generator
// Version: 1.0.0
//
// Auto-generated by py-openrpc-generator
// Target: github.com/gorilla/rpc/v2 (JSON-RPC 2.0)
// DO NOT EDIT — regenerate from the OpenRPC specification.

package main

import (
	"log"
	"net/http"

	"github.com/gorilla/rpc/v2"
	"github.com/gorilla/rpc/v2/json2"
)

// ============================================================================
// Type Definitions (from components/schemas)
// ============================================================================

type User struct {
	ID string `json:"id"`
	Name string `json:"name"`
	Email string `json:"email"`
	Age *int64 `json:"age,omitempty"`
	Status string `json:"status"`
	CreatedAt string `json:"createdAt"`
}

type UserServiceListResult struct {
	Items []User `json:"items"`
	Total int64 `json:"total"`
	Page int64 `json:"page"`
}

type DefaultServicePingResult struct {
	Result string `json:"result"`
}

// ============================================================================
// UserService — handles "user.*" RPC methods
//
// JSON-RPC method names are mapped as follows:
//   "<namespace>.<GoMethodName>" e.g. "user.MethodName"
// The json2 codec performs case-insensitive method name matching, so
// e.g. "user.getById" will match "user.GetById".
// ============================================================================

// UserServiceGetByIdArgs contains the arguments for user.getById.
type UserServiceGetByIdArgs struct {
	// The unique identifier of the user
	UserID string `json:"userId"`
}

// UserServiceGetByIdReply contains the result for user.getById.
type UserServiceGetByIdReply = User

// UserServiceCreateArgs contains the arguments for user.create.
type UserServiceCreateArgs struct {
	// User's full name
	Name string `json:"name"`
	// User's email address
	Email string `json:"email"`
	// User's age
	Age *int64 `json:"age,omitempty"`
}

// UserServiceCreateReply contains the result for user.create.
type UserServiceCreateReply = User

// UserServiceListArgs contains the arguments for user.list.
type UserServiceListArgs struct {
	// Page number
	Page *int64 `json:"page,omitempty"`
	// Number of items per page
	Limit *int64 `json:"limit,omitempty"`
}

// UserServiceListReply contains the result for user.list.
type UserServiceListReply = UserServiceListResult

// UserService implements the "user" RPC service.
// Register it with: server.RegisterService(new(UserService), "user")
type UserService struct{}

// GetById handles user.getById.
// Get user by ID
//
// Retrieves a user object by their unique identifier
func (s *UserService) GetById(r *http.Request, args *UserServiceGetByIdArgs, reply *UserServiceGetByIdReply) error {
	// TODO: implement user.getById
	return nil
}

// Create handles user.create.
// Create a new user
//
// Creates a new user with the provided information
func (s *UserService) Create(r *http.Request, args *UserServiceCreateArgs, reply *UserServiceCreateReply) error {
	// TODO: implement user.create
	return nil
}

// List handles user.list.
// List all users
//
// Retrieves a paginated list of users
func (s *UserService) List(r *http.Request, args *UserServiceListArgs, reply *UserServiceListReply) error {
	// TODO: implement user.list
	return nil
}

// ============================================================================
// DefaultService — handles "default.*" RPC methods
//
// JSON-RPC method names are mapped as follows:
//   "<namespace>.<GoMethodName>" e.g. "default.MethodName"
// The json2 codec performs case-insensitive method name matching, so
// e.g. "default.getById" will match "default.GetById".
// ============================================================================

// DefaultServicePingArgs contains the arguments for ping.
type DefaultServicePingArgs struct{}

// DefaultServicePingReply contains the result for ping.
type DefaultServicePingReply = DefaultServicePingResult

// DefaultService implements the "default" RPC service.
// Register it with: server.RegisterService(new(DefaultService), "")
type DefaultService struct{}

// Ping handles ping.
// Ping the server
//
// Simple health check endpoint
func (s *DefaultService) Ping(r *http.Request, args *DefaultServicePingArgs, reply *DefaultServicePingReply) error {
	// TODO: implement ping
	return nil
}

// ============================================================================
// Server Setup
// ============================================================================

func main() {
	server := rpc.NewServer()
	server.RegisterCodec(json2.NewCodec(), "application/json")

	if err := server.RegisterService(new(UserService), "user"); err != nil {
		log.Fatalf("failed to register UserService: %v", err)
	}
	if err := server.RegisterService(new(DefaultService), ""); err != nil {
		log.Fatalf("failed to register DefaultService: %v", err)
	}

	http.Handle("/rpc", server)

	port := "8080"
	log.Printf("JSON-RPC 2.0 server listening on :%s", port)
	log.Fatal(http.ListenAndServe(":"+port, nil))
}