/**
 * Example API
 * A sample API for testing the generator
 * Version: 1.0.0
 *
 * Auto-generated by py-openrpc-generator
 */

// ============================================================================
// Type Definitions
// ============================================================================

export interface User_getByIdParams {
  userId: string;
}

export interface User {
  id: string;
  name: string;
  email: string;
  age?: number;
  status: "active" | "inactive" | "suspended";
  createdAt: string;
}

export interface User_createParams {
  name: string;
  email: string;
  age?: number;
}

export interface User_listParams {
  page?: number;
  limit?: number;
}

export interface User_listResult {
  items: User[];
  total: number;
  page: number;
}

// ============================================================================
// JSON-RPC Infrastructure
// ============================================================================

interface JsonRpcRequest {
  jsonrpc: "2.0";
  method: string;
  params?: any;
  id: number | string;
}

interface JsonRpcResponse<T = any> {
  jsonrpc: "2.0";
  result?: T;
  error?: {
    code: number;
    message: string;
    data?: any;
  };
  id: number | string;
}

export class JsonRpcError extends Error {
  constructor(
    public code: number,
    message: string,
    public data?: any
  ) {
    super(`JSON-RPC Error ${code}: ${message}`);
    this.name = "JsonRpcError";
  }
}

// ============================================================================
// RPCClient
// ============================================================================

export class RPCClient {
  private url: string;
  private requestId: number = 0;

  constructor(url: string) {
    this.url = url;
  }

  private async request<T = any>(method: string, params?: any): Promise<T> {
    const id = ++this.requestId;
    const body: JsonRpcRequest = {
      jsonrpc: "2.0",
      method,
      params,
      id,
    };

    const response = await fetch(this.url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(body),
    });

    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }

    const data: JsonRpcResponse<T> = await response.json();

    if (data.error) {
      throw new JsonRpcError(data.error.code, data.error.message, data.error.data);
    }

    return data.result as T;
  }

  // ==========================================================================
  // API Methods
  // ==========================================================================

  /**
   * Get user by ID
   *
   * Retrieves a user object by their unique identifier
   * @param params - Method parameters
   *   - userId: The unique identifier of the user
   * @returns The user object
   */
  async user_getById(params: User_getByIdParams): Promise<User> {
    return this.request<User>("user.getById", params);
  }

  /**
   * Create a new user
   *
   * Creates a new user with the provided information
   * @param params - Method parameters
   *   - name: User's full name
   *   - email: User's email address
   *   - age: User's age
   * @returns The created user object
   */
  async user_create(params: User_createParams): Promise<User> {
    return this.request<User>("user.create", params);
  }

  /**
   * List all users
   *
   * Retrieves a paginated list of users
   * @param params - Method parameters
   *   - page: Page number
   *   - limit: Number of items per page
   * @returns List of users
   */
  async user_list(params: User_listParams): Promise<User_listResult> {
    return this.request<User_listResult>("user.list", params);
  }

  /**
   * Ping the server
   *
   * Simple health check endpoint
   * @returns Pong response
   */
  async ping(): Promise<"pong"> {
    return this.request<"pong">("ping");
  }
}